.pragma library

var DEFAULT_MARGIN = 16;
var BUTTON_SPACING = 6;

var HEADER_DEFAULT_BACKGROUND_COLOR = "#ff6600";

var HEADER_DEFAULT_HEIGHT_PORTRAIT = 72;
var HEADER_DEFAULT_HEIGHT_LANDSCAPE = 46;

var HEADER_DEFAULT_TOP_SPACING_PORTRAIT = 20;
var HEADER_DEFAULT_BOTTOM_SPACING_PORTRAIT = 20;

var HEADER_DEFAULT_TOP_SPACING_LANDSCAPE = 16;
var HEADER_DEFAULT_BOTTOM_SPACING_LANDSCAPE = 14;

var LIST_ITEM_HEIGHT_SMALL = 64;
var LIST_ITEM_HEIGHT_DEFAULT = 80;

var FONT_XLARGE = 32;
var FONT_XSMALL = 18;
var FONT_SLARGE = 26;
var FONT_DEFAULT = 24;
var FONT_LSMALL = 22;

var FONT_FAMILY = "Nokia Pure Text";
var FONT_FAMILY_BOLD = "Nokia Pure Text Bold";
var FONT_FAMILY_LIGHT = "Nokia Pure Text Light";

var PLAYER_COLORS = [ "blue", "orange", "dodgerblue", "peru", "olive", "mediumorchid", "darkkhaki" ];

var BACKGROUND_COLOR_TOP = "#f4952f"
var BACKGROUND_COLOR_BOTTOM = "#de3812"

var CREATE_BUTTON_SPACING = 30
var CREATE_BUTTON_WIDTH = 300
var CREATE_BUTTON_HEIGHT = 100
